version: "3"

# Services
services:
    # NGINX
    nginx:
        image: nginx:alpine
        restart: always
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/

            # Certbot/Let's Encrypt
            - ./certbot/conf/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
            - ./certbot/conf/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
            - ./volumes/certbot/conf:/etc/letsencrypt
            - ./volumes/certbot/www:/var/www/certbot
        networks:
            - example

    # Certbot
    certbot:
        image: certbot/certbot
        restart: always
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - ./volumes/certbot/conf:/etc/letsencrypt
            - ./volumes/certbot/www:/var/www/certbot
        networks:
            - example
# Networks
networks:
    example:
        name: example_network
